# Generated by Django 5.2 on 2025-04-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OfertaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('empresa', models.CharField(max_length=200)),
                ('ubicacion', models.CharField(max_length=200)),
                ('fecha_publicacion', models.DateField()),
                ('salario', models.CharField(blank=True, max_length=100, null=True)),
                ('url_oferta', models.URLField()),
                ('portal', models.CharField(max_length=100)),
                ('habilidades', models.ManyToManyField(to='busqueda.habilidad')),
            ],
        ),
    ]
