# Generated by Django 5.2 on 2025-04-24 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0002_notapersonal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatoMercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('industria', models.CharField(blank=True, max_length=100, null=True)),
                ('habilidad', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField(default=0)),
                ('portal', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InscripcionOferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busqueda.ofertalaboral')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
